# Speed tests for numpy ndarrays and for regular list arrays

Note! for two lists, list_1 and list_2 the +-sign is not calculating the lists component by component but is catenating two strings

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
list_1 = [1, 2, 3]
list_2 = [1, 2, 3]


In [3]:
list_1 + list_2

[1, 2, 3, 1, 2, 3]

Let's make this bit more interresting and initialize two lists and two ndarrays with really big number of values and then
see how long does it take for them sum the values up <ins>component wise</ins>

In [4]:
list_1 = list(range(100000000))
list_2 = list(range(100000000))

In [5]:
print(list_1[:5])
print(list_2[:5])

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


In [6]:
ndarray_1 = np.asarray(list_1)
ndarray_2 = np.asarray(list_2)

In [7]:
print(ndarray_1[:5])
print(ndarray_2[:5])

[0 1 2 3 4]
[0 1 2 3 4]


In [8]:
# Now summing the values of the two list component wise
list_3 =[]

for i in list_1:
    list_3.append(list_1[i] + list_2[i])

In [9]:
list_3[:5]

[0, 2, 4, 6, 8]

In [10]:
ndarray_3=ndarray_1 + ndarray_2

In [11]:
ndarray_3[:5]

array([0, 2, 4, 6, 8])